FROM python:3.12-slim

WORKDIR /app

ENV PYTHONPATH=/app
ENV FLASK_DEBUG=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "-m", "backend.api.tricount", "0.0.0.0"]
